services:
  angular-builder:
    build: .
    command: ["sh", "-c", "npm run build --prod && cp -r /app/dist/turnero/browser/* /app/build-output/"]
    volumes:
      - angular-static:/app/build-output
    networks:
      - serviciudad-network
    restart: "no"

  nginx:
    image: nginx:alpine
    volumes:
      - angular-static:/usr/share/nginx/html
    networks:
      - serviciudad-network
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  angular-static:
