version: '3.8'

services:
  angular-builder:
    build: .
    command: ["sh", "-c", "npm run build --prod && cp -r /app/dist/turnero/browser/* /output/"]
    volumes:
      - ./nginx/html:/output
    networks:
      - serviciudad-network
    restart: "no"

networks:
  serviciudad-network:
    external: true
