version: '3.8'

services:
  angular-app:
    build: .
    ports:
      - "80:80"
    networks:
      - serviciudad-network
    restart: unless-stopped

networks:
  serviciudad-network:
    external: true
